%YAML:1.0
StereoInfo:
  -
    Name: usbcam4g1_tltr
    CamL: 0
    CamR: 1
    Width: 320
    Height: 240
    StereoParam: config/usbcam4g1_tltr3.yaml
    StereoConfig: config/usbcam4g1_stereo.yaml
  -
    Name: usbcam4g1_blbr
    CamL: 2
    CamR: 3
    Width: 320
    Height: 240
    StereoParam: config/usbcam4g1_blbr1.yaml
    StereoConfig: config/usbcam4g1_stereo.yaml
